### ISSUE TITLE
Intervention image (2.x) broken

### ISSUE THREAD

**Issue by pecuchet** [gidlov/pico-gallery#1]
It seems that since Image 2.x the static method `make` is not available on the Image class anymore and `grab()` has been replaced by `fit()`. Because the README suggests using "dev-master" the plugin method `flush` should be updated with:

```
$img = new ImageManager();
$img->make($image)
    ->fit($size[0], $size[1])
    ->save($thumb_path.DIRECTORY_SEPARATOR.GALLERY_PRE_THUMB_NAME.$file_name, 80);
```

with `Intervention\Image\ImageManager` as namespace.

**Comment by gidlov** [comment]
Thanks pecuchet. It's done.
